'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.home': 'Home',
    'common.products': 'Products',
    'common.cart': 'Cart',
    'common.checkout': 'Checkout',
    'common.login': 'Login',
    'common.register': 'Register',
    'common.logout': 'Logout',
    'common.profile': 'Profile',
    'common.orders': 'Orders',
    'common.admin': 'Admin',
    'common.search': 'Search',
    'common.categories': 'Categories',
    'common.addToCart': 'Add to Cart',
    'common.buyNow': 'Buy Now',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.shipping': 'Shipping',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.noItems': 'No items found',
    'common.available': 'available',
    'common.category': 'Category',
    'common.view': 'View',
    // Home
    'home.title': 'Welcome to Ali76',
    'home.subtitle': 'Discover our beautiful collection',
    'home.featuredProducts': 'Featured Products',
    'home.shopNow': 'Shop Now',
    // Products
    'products.title': 'Our Products',
    'products.allProducts': 'All Products',
    'products.filter': 'Filter',
    'products.sortBy': 'Sort By',
    'products.priceLow': 'Price: Low to High',
    'products.priceHigh': 'Price: High to Low',
    'products.newest': 'Newest',
    'products.oldest': 'Oldest',
    'products.inStock': 'In Stock',
    'products.outOfStock': 'Out of Stock',
    // Product
    'product.description': 'Description',
    'product.specifications': 'Specifications',
    'product.reviews': 'Reviews',
    'product.relatedProducts': 'Related Products',
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.continueShopping': 'Continue Shopping',
    'cart.proceedToCheckout': 'Proceed to Checkout',
    'cart.addedToCart': '{name} added to cart',
    'cart.addToCartError': 'Failed to add product to cart',
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.shippingInfo': 'Shipping Information',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.orderSummary': 'Order Summary',
    'checkout.fullName': 'Full Name',
    'checkout.email': 'Email',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.country': 'Country',
    'checkout.postalCode': 'Postal Code',
    'checkout.phone': 'Phone',
    'checkout.placeOrder': 'Place Order',
    // Auth
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.loginTitle': 'Login to your account',
    'auth.registerTitle': 'Create an account',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.forgotPassword': 'Forgot password?',
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.products': 'Products',
    'admin.orders': 'Orders',
    'admin.categories': 'Categories',
    'admin.users': 'Users',
    'admin.addProduct': 'Add Product',
    'admin.editProduct': 'Edit Product',
    'admin.editProductDesc': 'Update product information',
    'admin.failedToUpdate': 'Failed to update product',
    'admin.productName': 'Product Name',
    'admin.productNameAr': 'Product Name (Arabic)',
    'admin.description': 'Description',
    'admin.descriptionAr': 'Description (Arabic)',
    'admin.price': 'Price',
    'admin.stock': 'Stock',
    'admin.images': 'Images',
    'admin.category': 'Category',
    'admin.featured': 'Featured',
    'admin.status': 'Status',
    'admin.pending': 'Pending',
    'admin.processing': 'Processing',
    'admin.shipped': 'Shipped',
    'admin.delivered': 'Delivered',
    'admin.cancelled': 'Cancelled',
    // Categories
    'categories.title': 'Our Categories',
    'categories.viewProducts': 'View Products',
    'categories.products': 'products',
    'categories.noCategories': 'No categories available',
    // About
    'about.title': 'About Us',
    'about.subtitle': 'Discover our story and values',
    'about.story': 'Our Story',
    'about.storyContent1': 'Ali76 was founded with a passion for bringing beautiful, high-quality products to our customers. We believe that shopping should be an enjoyable experience, filled with carefully curated items that bring joy to everyday life.',
    'about.storyContent2': 'Since our inception, we have been committed to providing exceptional customer service and a wide selection of products that meet the diverse needs of our community.',
    'about.mission': 'Our Mission',
    'about.missionContent': 'To provide our customers with the highest quality products and an exceptional shopping experience, while maintaining our commitment to customer satisfaction and community values.',
    'about.values': 'Our Values',
    'about.value1Title': 'Quality',
    'about.value1Content': 'We carefully select every product to ensure it meets our high standards of quality and durability.',
    'about.value2Title': 'Customer First',
    'about.value2Content': 'Your satisfaction is our priority. We strive to exceed expectations in every interaction.',
    'about.value3Title': 'Integrity',
    'about.value3Content': 'We conduct our business with honesty, transparency, and respect for our customers and community.',
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We would love to hear from you',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.address': 'Address',
    'contact.addressValue': 'حي الشاطي - جدة - المملكة العربية السعودية',
    'contact.businessHours': 'Business Hours',
    'contact.monday': 'Monday',
    'contact.tuesday': 'Tuesday',
    'contact.wednesday': 'Wednesday',
    'contact.thursday': 'Thursday',
    'contact.friday': 'Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.closed': 'Closed',
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions',
    'faq.question1': 'How do I place an order?',
    'faq.answer1': 'To place an order, simply browse our products, add items to your cart, and proceed to checkout. You will need to create an account or log in to complete your purchase.',
    'faq.question2': 'What payment methods do you accept?',
    'faq.answer2': 'We accept all major credit cards, debit cards, and PayPal. All payments are processed securely through our encrypted payment gateway.',
    'faq.question3': 'How long does shipping take?',
    'faq.answer3': 'Standard shipping typically takes 5-7 business days. Express shipping options are available at checkout for faster delivery (2-3 business days).',
    'faq.question4': 'Do you offer international shipping?',
    'faq.answer4': 'Currently, we ship within the country. International shipping options may be available for select products. Please contact us for more information.',
    'faq.question5': 'What is your return policy?',
    'faq.answer5': 'We offer a 30-day return policy for unused items in their original packaging. Items must be returned in the same condition they were received. Please contact us to initiate a return.',
    'faq.question6': 'How can I track my order?',
    'faq.answer6': 'Once your order ships, you will receive a tracking number via email. You can use this number to track your package on our website or the carrier\'s website.',
    'faq.question7': 'Can I modify or cancel my order?',
    'faq.answer7': 'Orders can be modified or cancelled within 24 hours of placement, provided they have not yet been shipped. Please contact our customer service team as soon as possible.',
    'faq.question8': 'Do you have a physical store?',
    'faq.answer8': 'Currently, we operate as an online-only store. However, we are always looking to expand and may open physical locations in the future. Stay tuned for updates!',
    'faq.stillHaveQuestions': 'Still have questions?',
    'faq.contactUs': 'If you couldn\'t find the answer you were looking for, please don\'t hesitate to contact us.',
    'faq.contactButton': 'Contact Us',
    // Favorites
    'favorites.title': 'My Favorites',
    'favorites.empty': 'No favorites yet',
    'favorites.emptyDescription': 'Start adding products to your favorites list',
    'favorites.browseProducts': 'Browse Products',
    'favorites.remove': 'Remove',
    // Profile
    'profile.title': 'My Profile',
    'profile.edit': 'Edit Profile',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.namePlaceholder': 'Enter your name',
    'profile.emailPlaceholder': 'Enter your email',
    'profile.noName': 'Not set',
    'profile.memberSince': 'Member Since',
    'profile.role': 'Role',
    'profile.orderHistory': 'Order History',
    'profile.noOrders': 'No orders yet',
    'profile.noOrdersDescription': 'You haven\'t placed any orders yet',
    'profile.startShopping': 'Start Shopping',
    'profile.orderId': 'Order ID',
    'profile.orderDate': 'Order Date',
    'profile.orderTotal': 'Total',
    'profile.orderItems': 'Order Items',
    'profile.shippingAddress': 'Shipping Address',
    'profile.orderStatus.pending': 'Pending',
    'profile.orderStatus.processing': 'Processing',
    'profile.orderStatus.shipped': 'Shipped',
    'profile.orderStatus.delivered': 'Delivered',
    'profile.orderStatus.cancelled': 'Cancelled',
    'profile.orderStatus.unknown': 'Unknown',
    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'Your privacy is important to us',
    'privacy.lastUpdated': 'Last Updated',
    'privacy.introduction': 'Introduction',
    'privacy.introContent1': 'At Ali76, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website and use our services.',
    'privacy.introContent2': 'By using our website, you agree to the collection and use of information in accordance with this policy. If you do not agree with our policies and practices, please do not use our services.',
    'privacy.informationWeCollect': 'Information We Collect',
    'privacy.personalInfo': 'Personal Information',
    'privacy.personalInfoContent': 'We collect personal information that you voluntarily provide to us when you register for an account, place an order, or contact us. This may include your name, email address, phone number, shipping address, and payment information.',
    'privacy.usageData': 'Usage Data',
    'privacy.usageDataContent': 'We automatically collect certain information when you visit our website, including your IP address, browser type, device information, pages visited, and time spent on our site. This helps us improve our services and user experience.',
    'privacy.cookies': 'Cookies and Tracking Technologies',
    'privacy.cookiesContent': 'We use cookies and similar tracking technologies to track activity on our website and store certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.',
    'privacy.howWeUse': 'How We Use Your Information',
    'privacy.useItem1': 'To process and fulfill your orders',
    'privacy.useItem2': 'To communicate with you about your orders and provide customer support',
    'privacy.useItem3': 'To send you marketing communications (with your consent)',
    'privacy.useItem4': 'To improve our website and services',
    'privacy.useItem5': 'To detect and prevent fraud and abuse',
    'privacy.dataProtection': 'Data Protection',
    'privacy.dataProtectionContent1': 'We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the Internet is 100% secure.',
    'privacy.dataProtectionContent2': 'We retain your personal information only for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required by law.',
    'privacy.yourRights': 'Your Rights',
    'privacy.rightItem1': 'Access: You have the right to access the personal information we hold about you',
    'privacy.rightItem2': 'Correction: You can request correction of inaccurate or incomplete information',
    'privacy.rightItem3': 'Deletion: You may request deletion of your personal information',
    'privacy.rightItem4': 'Objection: You can object to processing of your personal information for certain purposes',
    'privacy.contactUs': 'Contact Us',
    'privacy.contactContent': 'If you have any questions about this Privacy Policy or wish to exercise your rights, please contact us:',
    'privacy.email': 'Email',
    // Terms of Service
    'terms.title': 'Terms of Service',
    'terms.subtitle': 'Please read these terms carefully',
    'terms.lastUpdated': 'Last Updated',
    'terms.acceptance': 'Acceptance of Terms',
    'terms.acceptanceContent1': 'By accessing and using the Ali76 website, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.',
    'terms.acceptanceContent2': 'These Terms of Service constitute a legally binding agreement between you and Ali76. We reserve the right to modify these terms at any time, and such modifications will be effective immediately upon posting.',
    'terms.useOfService': 'Use of Service',
    'terms.eligibility': 'Eligibility',
    'terms.eligibilityContent': 'You must be at least 18 years old to use our services. By using our website, you represent and warrant that you are of legal age to form a binding contract and meet all eligibility requirements.',
    'terms.account': 'Account Registration',
    'terms.accountContent': 'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.',
    'terms.products': 'Products and Pricing',
    'terms.productsContent1': 'We strive to provide accurate product descriptions, images, and pricing information. However, we do not warrant that product descriptions or other content on this site is accurate, complete, reliable, current, or error-free.',
    'terms.productsContent2': 'Prices are subject to change without notice. We reserve the right to modify or discontinue products at any time without prior notice.',
    'terms.orders': 'Orders and Payment',
    'terms.orderItem1': 'All orders are subject to product availability and our acceptance',
    'terms.orderItem2': 'We reserve the right to refuse or cancel any order for any reason',
    'terms.orderItem3': 'Payment must be received before we ship your order',
    'terms.orderItem4': 'All prices are in USD unless otherwise stated',
    'terms.payment': 'Payment Terms',
    'terms.paymentContent1': 'We accept various payment methods including credit cards, debit cards, and other payment methods as indicated on our website. By providing payment information, you represent that you are authorized to use the payment method.',
    'terms.paymentContent2': 'You agree to pay all charges incurred by your use of the service. All prices are subject to change without notice.',
    'terms.returns': 'Returns and Refunds',
    'terms.returnsContent1': 'We offer a 30-day return policy for unused items in their original packaging. Items must be returned in the same condition they were received.',
    'terms.returnsContent2': 'To initiate a return, please contact our customer service team. Refunds will be processed to the original payment method within 5-10 business days after we receive and inspect the returned item.',
    'terms.limitation': 'Limitation of Liability',
    'terms.limitationContent': 'To the fullest extent permitted by law, Ali76 shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses.',
    'terms.changes': 'Changes to Terms',
    'terms.changesContent': 'We reserve the right to modify or replace these Terms of Service at any time. If a revision is material, we will provide at least 30 days notice prior to any new terms taking effect. Your continued use of the service after any changes constitutes acceptance of those changes.',
    'terms.contact': 'Contact Information',
    'terms.contactContent': 'If you have any questions about these Terms of Service, please contact us:',
    'terms.email': 'Email',
    // Footer
    'footer.shop': 'Shop',
    'footer.company': 'Company',
    'footer.information': 'Information',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.faq': 'FAQ',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.shippingPolicy': 'Shipping Policy',
    'footer.contactUs': 'Contact Us',
    'footer.description': 'Discover our beautiful collection of high-quality products',
    'footer.allRightsReserved': 'All rights reserved',
    'footer.contactUsForFeedback': 'Contact us for any feedback',
    'footer.madeWith': 'Made with',
    'footer.in': 'in',
  },
  ar: {
    // Common
    'common.home': 'الرئيسية',
    'common.products': 'المنتجات',
    'common.cart': 'السلة',
    'common.checkout': 'الدفع',
    'common.login': 'تسجيل الدخول',
    'common.register': 'إنشاء حساب',
    'common.logout': 'تسجيل الخروج',
    'common.profile': 'حسابي',
    'common.orders': 'الطلبات',
    'common.admin': 'الإدارة',
    'common.search': 'بحث',
    'common.categories': 'الفئات',
    'common.addToCart': 'أضف إلي السلة',
    'common.buyNow': 'اشتري الآن',
    'common.price': 'السعر',
    'common.quantity': 'الكمية',
    'common.total': 'المجموع',
    'common.subtotal': 'المجموع الفرعي',
    'common.shipping': 'الشحن',
    'common.continue': 'متابعة',
    'common.back': 'رجوع',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.create': 'إنشاء',
    'common.update': 'تحديث',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.noItems': 'لا توجد عناصر',
    'common.available': 'متوفر',
    'common.category': 'الفئة',
    // Home
    'home.title': 'مرحباً بك في Ali76',
    'home.subtitle': 'اكتشف مجموعتنا الجميلة',
    'home.featuredProducts': 'المنتجات المميزة',
    'home.shopNow': 'تسوق الآن',
    // Products
    'products.title': 'منتجاتنا',
    'products.allProducts': 'جميع المنتجات',
    'products.filter': 'تصفية',
    'products.sortBy': 'ترتيب حسب',
    'products.priceLow': 'السعر: من الأقل للأعلي',
    'products.priceHigh': 'السعر: من الأعلي للأقل',
    'products.newest': 'الأحدث',
    'products.oldest': 'الأقدم',
    'products.inStock': 'متوفر',
    'products.outOfStock': 'غير متوفر',
    // Product
    'product.description': 'الوصف',
    'product.specifications': 'المواصفات',
    'product.reviews': 'التقييمات',
    'product.relatedProducts': 'منتجات ذات صلة',
    // Cart
    'cart.title': 'سلة التسوق',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.continueShopping': 'متابعة التسوق',
    'cart.proceedToCheckout': 'المتابعة للدفع',
    'cart.addedToCart': 'تم إضافة {name} إلى السلة',
    'cart.addToCartError': 'فشل إضافة المنتج إلى السلة',
    // Checkout
    'checkout.title': 'الدفع',
    'checkout.shippingInfo': 'معلومات الشحن',
    'checkout.paymentMethod': 'طريقة الدفع',
    'checkout.orderSummary': 'ملخص الطلب',
    'checkout.fullName': 'الاسم الكامل',
    'checkout.email': 'البريد الإلكتروني',
    'checkout.address': 'العنوان',
    'checkout.city': 'المدينة',
    'checkout.country': 'الدولة',
    'checkout.postalCode': 'الرمز البريدي',
    'checkout.phone': 'الهاتف',
    'checkout.placeOrder': 'تقديم الطلب',
    // Auth
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.name': 'الاسم',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'إنشاء حساب',
    'auth.loginTitle': 'تسجيل الدخول',
    'auth.registerTitle': 'إنشاء حساب',
    'auth.alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'auth.dontHaveAccount': 'ليس لديك حساب؟',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    // Admin
    'admin.dashboard': 'لوحة التحكم',
    'admin.products': 'المنتجات',
    'admin.orders': 'الطلبات',
    'admin.categories': 'الفئات',
    'admin.users': 'المستخدمون',
    'admin.addProduct': 'إضافة منتج',
    'admin.editProduct': 'تعديل منتج',
    'admin.editProductDesc': 'تحديث معلومات المنتج',
    'admin.failedToUpdate': 'فشل تحديث المنتج',
    'admin.productName': 'اسم المنتج',
    'admin.productNameAr': 'اسم المنتج (عربي)',
    'admin.description': 'الوصف',
    'admin.descriptionAr': 'الوصف (عربي)',
    'admin.price': 'السعر',
    'admin.stock': 'المخزون',
    'admin.images': 'الصور',
    'admin.category': 'الفئة',
    'admin.featured': 'مميز',
    'admin.status': 'الحالة',
    'admin.pending': 'قيد الانتظار',
    'admin.processing': 'قيد المعالجة',
    'admin.shipped': 'تم الشحن',
    'admin.delivered': 'تم التسليم',
    'admin.cancelled': 'ملغي',
    'admin.totalRevenue': 'إجمالي الإيرادات',
    'admin.pendingOrders': 'الطلبات المعلقة',
    'admin.recentOrders': 'الطلبات الأخيرة',
    'admin.viewAll': 'عرض الكل',
    'admin.quickActions': 'إجراءات سريعة',
    'admin.welcome': 'مرحباً بك في لوحة التحكم',
    'admin.manageStore': 'إدارة متجرك الإلكتروني بأدوات قوية',
    'admin.createProduct': 'إنشاء منتج جديد',
    'admin.addNewProduct': 'إضافة منتج جديد',
    'admin.viewOrders': 'عرض الطلبات',
    'admin.manageOrders': 'إدارة جميع الطلبات',
    'admin.manageCategories': 'إدارة الفئات',
    'admin.orderId': 'رقم الطلب',
    'admin.customer': 'العميل',
    'admin.date': 'التاريخ',
    'admin.total': 'المجموع',
    'admin.redirecting': 'جاري إعادة التوجيه...',
    'admin.viewSite': 'عرض الموقع',
    'admin.logout': 'تسجيل الخروج',
    'admin.panel': 'لوحة الإدارة',
    'admin.name': 'الاسم',
    'admin.priceLabel': 'السعر',
    'admin.stockLabel': 'المخزون',
    'admin.categoryLabel': 'الفئة',
    'admin.featuredLabel': 'مميز',
    'admin.actions': 'الإجراءات',
    'admin.yes': 'نعم',
    'admin.no': 'لا',
    'admin.createYourFirstProduct': 'أنشئ منتجك الأول',
    'admin.noProductsFound': 'لا توجد منتجات',
    'admin.backToProducts': 'العودة إلي المنتجات',
    'admin.addProductDesc': 'إضافة منتج جديد',
    'admin.productNameEn': 'اسم المنتج (إنجليزي)',
    'admin.descriptionEn': 'الوصف (إنجليزي)',
    'admin.priceDollar': 'السعر ($)',
    'admin.stockQuantity': 'الكمية في المخزون',
    'admin.productImages': 'صور المنتج (روابط)',
    'admin.enterImageUrl': 'أدخل رابط الصورة واضغط Enter أو انقر علي إضافة',
    'admin.add': 'إضافة',
    'admin.markAsFeatured': 'تعيين كمنتج مميز',
    'admin.creating': 'جاري الإنشاء...',
    'admin.createProductButton': 'إنشاء المنتج',
    'admin.fillRequiredFields': 'يرجي ملء جميع الحقول المطلوبة',
    'admin.failedToCreate': 'فشل إنشاء المنتج',
    'admin.selectCategory': 'اختر فئة',
    // Categories
    'categories.title': 'فئاتنا',
    'categories.viewProducts': 'عرض المنتجات',
    'categories.products': 'منتج',
    'categories.noCategories': 'لا توجد فئات متاحة',
    // About
    'about.title': 'من نحن',
    'about.subtitle': 'اكتشف قصتنا وقيمنا',
    'about.story': 'قصتنا',
    'about.storyContent1': 'تأسس Ali76 بشغف لجلب منتجات جميلة وعالية الجودة لعملائنا. نؤمن بأن التسوق يجب أن يكون تجربة ممتعة، مليئة بالعناصر المختارة بعناية التي تجلب الفرح للحياة اليومية.',
    'about.storyContent2': 'منذ تأسيسنا، كنا ملتزمين بتقديم خدمة عملاء استثنائية ومجموعة واسعة من المنتجات التي تلبي الاحتياجات المتنوعة لمجتمعنا.',
    'about.mission': 'مهمتنا',
    'about.missionContent': 'تقديم أعلي جودة من المنتجات وتجربة تسوق استثنائية لعملائنا، مع الحفاظ علي التزامنا برضا العملاء وقيم المجتمع.',
    'about.values': 'قيمنا',
    'about.value1Title': 'الجودة',
    'about.value1Content': 'نختار كل منتج بعناية لضمان أنه يلبي معاييرنا العالية للجودة والمتانة.',
    'about.value2Title': 'العميل أولاً',
    'about.value2Content': 'رضاك هو أولويتنا. نسعي جاهدين لتجاوز التوقعات في كل تفاعل.',
    'about.value3Title': 'النزاهة',
    'about.value3Content': 'نقوم بأعمالنا بأمانة وشفافية واحترام لعملائنا ومجتمعنا.',
    // Contact
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'نود أن نسمع منك',
    'contact.email': 'البريد الإلكتروني',
    'contact.phone': 'الهاتف',
    'contact.address': 'العنوان',
    'contact.addressValue': 'حي الشاطي - جدة - المملكة العربية السعودية',
    'contact.businessHours': 'ساعات العمل',
    'contact.monday': 'الاثنين',
    'contact.tuesday': 'الثلاثاء',
    'contact.wednesday': 'الأربعاء',
    'contact.thursday': 'الخميس',
    'contact.friday': 'الجمعة',
    'contact.saturday': 'السبت',
    'contact.sunday': 'الأحد',
    'contact.closed': 'مغلق',
    // FAQ
    'faq.title': 'الأسئلة الشائعة',
    'faq.subtitle': 'ابحث عن إجابات للأسئلة الشائعة',
    'faq.question1': 'كيف يمكنني تقديم طلب؟',
    'faq.answer1': 'لتقديم طلب، ببساطة تصفح منتجاتنا، أضف العناصر إلي سلة التسوق، وتابع إلي الدفع. ستحتاج إلي إنشاء حساب أو تسجيل الدخول لإكمال عملية الشراء.',
    'faq.question2': 'ما هي طرق الدفع التي تقبلونها؟',
    'faq.answer2': 'نقبل جميع بطاقات الائتمان الرئيسية وبطاقات الخصم وباي بال. تتم معالجة جميع المدفوعات بأمان من خلال بوابة الدفع المشفرة.',
    'faq.question3': 'كم يستغرق الشحن؟',
    'faq.answer3': 'عادة ما يستغرق الشحن القياسي 5-7 أيام عمل. خيارات الشحن السريع متاحة عند الدفع لتسليم أسرع (2-3 أيام عمل).',
    'faq.question4': 'هل تقدمون شحناً دولياً؟',
    'faq.answer4': 'حالياً، نقوم بالشحن داخل الدولة. قد تكون خيارات الشحن الدولي متاحة لبعض المنتجات المحددة. يرجي الاتصال بنا لمزيد من المعلومات.',
    'faq.question5': 'ما هي سياسة الإرجاع الخاصة بكم؟',
    'faq.answer5': 'نوفر سياسة إرجاع لمدة 30 يوماً للعناصر غير المستخدمة في عبواتها الأصلية. يجب إرجاع العناصر بنفس الحالة التي تم استلامها بها. يرجي الاتصال بنا لبدء عملية الإرجاع.',
    'faq.question6': 'كيف يمكنني تتبع طلبي؟',
    'faq.answer6': 'بمجرد شحن طلبك، ستحصل علي رقم تتبع عبر البريد الإلكتروني. يمكنك استخدام هذا الرقم لتتبع شحنتك علي موقعنا أو موقع الناقل.',
    'faq.question7': 'هل يمكنني تعديل أو إلغاء طلبي؟',
    'faq.answer7': 'يمكن تعديل أو إلغاء الطلبات خلال 24 ساعة من تقديمها، بشرط ألا تكون قد تم شحنها بعد. يرجي الاتصال بفريق خدمة العملاء في أقرب وقت ممكن.',
    'faq.question8': 'هل لديكم متجر فعلي؟',
    'faq.answer8': 'حالياً، نعمل كمتجر عبر الإنترنت فقط. ومع ذلك، نحن نبحث دائماً عن التوسع وقد نفتح مواقع فعلية في المستقبل. ترقبوا التحديثات!',
    'faq.stillHaveQuestions': 'لا تزال لديك أسئلة؟',
    'faq.contactUs': 'إذا لم تجد الإجابة التي تبحث عنها، يرجي عدم التردد في الاتصال بنا.',
    'faq.contactButton': 'اتصل بنا',
    // Favorites
    'favorites.title': 'مفضلاتي',
    'favorites.empty': 'لا توجد مفضلات بعد',
    'favorites.emptyDescription': 'ابدأ بإضافة المنتجات إلي قائمة المفضلة',
    'favorites.browseProducts': 'تصفح المنتجات',
    'favorites.remove': 'إزالة',
    // Profile
    'profile.title': 'حسابي',
    'profile.edit': 'تعديل الملف الشخصي',
    'profile.name': 'الاسم',
    'profile.email': 'البريد الإلكتروني',
    'profile.namePlaceholder': 'أدخل اسمك',
    'profile.emailPlaceholder': 'أدخل بريدك الإلكتروني',
    'profile.noName': 'غير محدد',
    'profile.memberSince': 'عضو منذ',
    'profile.role': 'الدور',
    'profile.orderHistory': 'سجل الطلبات',
    'profile.noOrders': 'لا توجد طلبات بعد',
    'profile.noOrdersDescription': 'لم تقم بتقديم أي طلبات بعد',
    'profile.startShopping': 'ابدأ التسوق',
    'profile.orderId': 'رقم الطلب',
    'profile.orderDate': 'تاريخ الطلب',
    'profile.orderTotal': 'المجموع',
    'profile.orderItems': 'عناصر الطلب',
    'profile.shippingAddress': 'عنوان الشحن',
    'profile.orderStatus.pending': 'قيد الانتظار',
    'profile.orderStatus.processing': 'قيد المعالجة',
    'profile.orderStatus.shipped': 'تم الشحن',
    'profile.orderStatus.delivered': 'تم التسليم',
    'profile.orderStatus.cancelled': 'ملغي',
    'profile.orderStatus.unknown': 'غير معروف',
    // Privacy Policy
    'privacy.title': 'سياسة الخصوصية',
    'privacy.subtitle': 'خصوصيتك مهمة بالنسبة لنا',
    'privacy.lastUpdated': 'آخر تحديث',
    'privacy.introduction': 'مقدمة',
    'privacy.introContent1': 'نحن ملتزمون بحماية خصوصيتك وضمان أمان معلوماتك الشخصية. توضح سياسة الخصوصية هذه كيفية جمع واستخدام وكشف وحماية معلوماتك عند زيارة موقعنا واستخدام خدماتنا.',
    'privacy.introContent2': 'باستخدام موقعنا، فإنك توافق علي جمع واستخدام المعلومات وفقًا لهذه السياسة. إذا كنت لا توافق علي سياساتنا وممارساتنا، يرجي عدم استخدام خدماتنا.',
    'privacy.informationWeCollect': 'المعلومات التي نجمعها',
    'privacy.personalInfo': 'المعلومات الشخصية',
    'privacy.personalInfoContent': 'نجمع المعلومات الشخصية التي تقدمها لنا طواعية عند التسجيل للحصول علي حساب أو تقديم طلب أو الاتصال بنا. قد يشمل ذلك اسمك وعنوان بريدك الإلكتروني ورقم هاتفك وعنوان الشحن ومعلومات الدفع.',
    'privacy.usageData': 'بيانات الاستخدام',
    'privacy.usageDataContent': 'نجمع تلقائيًا معلومات معينة عند زيارة موقعنا، بما في ذلك عنوان IP الخاص بك ونوع المتصفح ومعلومات الجهاز والصفحات التي تمت زيارتها والوقت الذي تقضيه علي موقعنا. يساعدنا هذا في تحسين خدماتنا وتجربة المستخدم.',
    'privacy.cookies': 'ملفات تعريف الارتباط وتقنيات التتبع',
    'privacy.cookiesContent': 'نستخدم ملفات تعريف الارتباط وتقنيات التتبع المماثلة لتتبع النشاط علي موقعنا وتخزين معلومات معينة. يمكنك توجيه متصفحك لرفض جميع ملفات تعريف الارتباط أو للإشارة عند إرسال ملف تعريف ارتباط.',
    'privacy.howWeUse': 'كيف نستخدم معلوماتك',
    'privacy.useItem1': 'لمعالجة وتنفيذ طلباتك',
    'privacy.useItem2': 'للتواصل معك بشأن طلباتك وتقديم دعم العملاء',
    'privacy.useItem3': 'لإرسال رسائل تسويقية إليك (بموافقتك)',
    'privacy.useItem4': 'لتحسين موقعنا وخدماتنا',
    'privacy.useItem5': 'لاكتشاف ومنع الاحتيال وإساءة الاستخدام',
    'privacy.dataProtection': 'حماية البيانات',
    'privacy.dataProtectionContent1': 'ننفذ تدابير أمنية تقنية وتنظيمية مناسبة لحماية معلوماتك الشخصية ضد الوصول غير المصرح به أو التعديل أو الكشف أو التدمير. ومع ذلك، لا توجد طريقة نقل عبر الإنترنت آمنة بنسبة 100%.',
    'privacy.dataProtectionContent2': 'نحتفظ بمعلوماتك الشخصية فقط طالما كان ذلك ضروريًا لتحقيق الأغراض الموضحة في سياسة الخصوصية هذه، ما لم تتطلب فترة احتفاظ أطول بموجب القانون.',
    'privacy.yourRights': 'حقوقك',
    'privacy.rightItem1': 'الوصول: لديك الحق في الوصول إلي المعلومات الشخصية التي نحتفظ بها عنك',
    'privacy.rightItem2': 'التصحيح: يمكنك طلب تصحيح المعلومات غير الدقيقة أو غير الكاملة',
    'privacy.rightItem3': 'الحذف: يمكنك طلب حذف معلوماتك الشخصية',
    'privacy.rightItem4': 'الاعتراض: يمكنك الاعتراض علي معالجة معلوماتك الشخصية لأغراض معينة',
    'privacy.contactUs': 'اتصل بنا',
    'privacy.contactContent': 'إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه أو ترغب في ممارسة حقوقك، يرجي الاتصال بنا:',
    'privacy.email': 'البريد الإلكتروني',
    // Terms of Service
    'terms.title': 'شروط الخدمة',
    'terms.subtitle': 'يرجي قراءة هذه الشروط بعناية',
    'terms.lastUpdated': 'آخر تحديث',
    'terms.acceptance': 'قبول الشروط',
    'terms.acceptanceContent1': 'من خلال الوصول إلي موقع Ali76 واستخدامه، فإنك تقبل وتوافق علي الالتزام بشروط وأحكام هذه الاتفاقية. إذا كنت لا توافق علي الالتزام بما سبق، يرجي عدم استخدام هذه الخدمة.',
    'terms.acceptanceContent2': 'تشكل شروط الخدمة هذه اتفاقية ملزمة قانونيًا بينك وبين Ali76. نحتفظ بالحق في تعديل هذه الشروط في أي وقت، وستكون هذه التعديلات سارية فور النشر.',
    'terms.useOfService': 'استخدام الخدمة',
    'terms.eligibility': 'الأهلية',
    'terms.eligibilityContent': 'يجب أن تكون في سن 18 عامًا علي الأقل لاستخدام خدماتنا. باستخدام موقعنا، فإنك تمثل وتضمن أنك في سن قانونية لتكوين عقد ملزم وتلبية جميع متطلبات الأهلية.',
    'terms.account': 'تسجيل الحساب',
    'terms.accountContent': 'أنت مسؤول عن الحفاظ علي سرية بيانات اعتماد حسابك وعن جميع الأنشطة التي تحدث تحت حسابك. توافق علي إخطارنا فورًا بأي استخدام غير مصرح به لحسابك.',
    'terms.products': 'المنتجات والأسعار',
    'terms.productsContent1': 'نسعي جاهدين لتوفير أوصاف دقيقة للمنتجات والصور ومعلومات الأسعار. ومع ذلك، لا نضمن أن أوصاف المنتجات أو المحتوي الآخر علي هذا الموقع دقيق أو كامل أو موثوق أو حديث أو خالٍ من الأخطاء.',
    'terms.productsContent2': 'الأسعار قابلة للتغيير دون إشعار. نحتفظ بالحق في تعديل أو إيقاف المنتجات في أي وقت دون إشعار مسبق.',
    'terms.orders': 'الطلبات والدفع',
    'terms.orderItem1': 'جميع الطلبات خاضعة لتوفر المنتج وقبولنا',
    'terms.orderItem2': 'نحتفظ بالحق في رفض أو إلغاء أي طلب لأي سبب',
    'terms.orderItem3': 'يجب استلام الدفع قبل شحن طلبك',
    'terms.orderItem4': 'جميع الأسعار بالدولار الأمريكي ما لم يُذكر خلاف ذلك',
    'terms.payment': 'شروط الدفع',
    'terms.paymentContent1': 'نقبل طرق دفع مختلفة بما في ذلك بطاقات الائتمان وبطاقات الخصم وطرق الدفع الأخري كما هو موضح علي موقعنا. من خلال تقديم معلومات الدفع، فإنك تمثل أنك مخول لاستخدام طريقة الدفع.',
    'terms.paymentContent2': 'أنت توافق علي دفع جميع الرسوم المتكبدة من استخدامك للخدمة. جميع الأسعار قابلة للتغيير دون إشعار.',
    'terms.returns': 'الإرجاع والاسترداد',
    'terms.returnsContent1': 'نوفر سياسة إرجاع لمدة 30 يومًا للعناصر غير المستخدمة في عبواتها الأصلية. يجب إرجاع العناصر بنفس الحالة التي تم استلامها بها.',
    'terms.returnsContent2': 'لبدء عملية الإرجاع، يرجي الاتصال بفريق خدمة العملاء لدينا. سيتم معالجة المبالغ المستردة إلي طريقة الدفع الأصلية خلال 5-10 أيام عمل بعد استلامنا وفحص العنصر المرتجع.',
    'terms.limitation': 'تحديد المسؤولية',
    'terms.limitationContent': 'إلي أقصي حد يسمح به القانون، لن يكون Ali76 مسؤولاً عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو عقابية، أو أي خسارة في الأرباح أو الإيرادات، سواء تم تكبدها مباشرة أو غير مباشرة، أو أي خسارة في البيانات أو الاستخدام أو السمعة التجارية أو الخسائر غير الملموسة الأخري.',
    'terms.changes': 'تغييرات الشروط',
    'terms.changesContent': 'نحتفظ بالحق في تعديل أو استبدال شروط الخدمة هذه في أي وقت. إذا كان التنقيح مهمًا، فسنوفر إشعارًا لمدة 30 يومًا علي الأقل قبل سريان أي شروط جديدة. استمرارك في استخدام الخدمة بعد أي تغييرات يشكل قبولًا لتلك التغييرات.',
    'terms.contact': 'معلومات الاتصال',
    'terms.contactContent': 'إذا كان لديك أي أسئلة حول شروط الخدمة هذه، يرجي الاتصال بنا:',
    'terms.email': 'البريد الإلكتروني',
    // Footer
    'footer.shop': 'تسوق',
    'footer.company': 'الشركة',
    'footer.information': 'معلومات',
    'footer.aboutUs': 'من نحن',
    'footer.contact': 'اتصل بنا',
    'footer.faq': 'الأسئلة الشائعة',
    'footer.privacyPolicy': 'سياسة الخصوصية',
    'footer.termsOfService': 'شروط الخدمة',
    'footer.shippingPolicy': 'سياسة الشحن',
    'footer.contactUs': 'تواصل معنا',
    'footer.description': 'اكتشف مجموعتنا الجميلة من المنتجات عالية الجودة',
    'footer.allRightsReserved': 'جميع الحقوق محفوظة',
    'footer.contactUsForFeedback': 'راسلنا لأي ملاحظة',
    'footer.madeWith': 'صُنع بـ',
    'footer.in': 'في',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang === 'en' || savedLang === 'ar') {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    // Update HTML dir attribute
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    // Set initial dir and lang
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

